steps:
  - name: gcr.io/cloud-builders/docker
    id: Build container image
    args:
      [
        'build',
        '-t',
        '$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/backend:$COMMIT_SHA',
        'backend'
      ]

  - name: gcr.io/cloud-builders/docker
    id: Push container image
    args:
      [
        'push',
        '$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/backend:$COMMIT_SHA'
      ]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy to Cloud Run
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'talkingskull-backend',
        '--image=$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/backend:$COMMIT_SHA',
        '--region=$LOCATION',
        '--platform=managed',
        '--allow-unauthenticated',
        '--set-env-vars',
        'LIVEKIT_HOST=${_LIVEKIT_HOST}',
        'LIVEKIT_TOKEN_TTL=${_LIVEKIT_TOKEN_TTL}',
        '--set-secrets',
        'LIVEKIT_API_KEY=${_LIVEKIT_API_KEY}:latest',
        'LIVEKIT_API_SECRET=${_LIVEKIT_API_SECRET}:latest'
      ]
images:
  - '$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/backend:$COMMIT_SHA'
substitutions:
  _LIVEKIT_HOST: https://your-livekit-host
  _LIVEKIT_TOKEN_TTL: '3600'
  _LIVEKIT_API_KEY: projects/PROJECT_ID/secrets/livekit-api-key
  _LIVEKIT_API_SECRET: projects/PROJECT_ID/secrets/livekit-api-secret
options:
  logging: CLOUD_LOGGING_ONLY
